name: nomercy
description: "nomercy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flame: ^1.17.0
  flame_forge2d: ^0.17.0
  flame_audio: ^2.11.12
  socket_io_client: ^2.0.3
  cupertino_icons: ^1.0.8
  gamepads: ^0.1.9
  font_awesome_flutter: ^10.7.0
  core:
    path: modules/core
  engine:
    path: modules/engine
  ui:
    path: modules/ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/knight.png
    - assets/images/knight_attack.png
    - assets/images/knight_jump.png
    - assets/images/knight_walk.png
    - assets/images/knight_idle.png
    - assets/images/knight_landing.png
    - assets/images/thief.png
    - assets/images/thief_attack.png
    - assets/images/thief_jump.png
    - assets/images/thief_walk.png
    - assets/images/thief_idle.png
    - assets/images/thief_landing.png
    - assets/images/wizard.png
    - assets/images/wizard_attack.png
    - assets/images/wizard_jump.png
    - assets/images/wizard_walk.png
    - assets/images/wizard_idle.png
    - assets/images/wizard_landing.png
    - assets/images/trader.png
    - assets/images/trader_attack.png
    - assets/images/trader_jump.png
    - assets/images/trader_walk.png
    - assets/images/trader_idle.png
    - assets/images/trader_landing.png
    - assets/images/brick.png
    - assets/images/stone.png
    - assets/images/ground.png
    - assets/images/brick_overlay.png
    - assets/images/stone_overlay.png
    - assets/images/ground_overlay.png
    - assets/images/brick_tile.png
    - assets/images/ground_tile.png
    - assets/images/dower_chest.png
    - assets/images/dower_chest_opened.png
    - assets/images/health_potion.png
    - assets/audio/hit.wav
    - assets/audio/death.wav
    - assets/audio/jump.wav
    - assets/audio/block.wav
    - assets/audio/combo.wav
    - assets/audio/dagger_shot.wav
    - assets/audio/arrow_shot.wav
    - assets/audio/battle_theme.wav
    - assets/maps/
    - assets/maps/level_1.json
    - assets/maps/level_2.json
    - assets/maps/level_3.json
