name: nomercy
description: "nomercy"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.17.0
  flame_forge2d: ^0.17.0
  socket_io_client: ^2.0.3
  cupertino_icons: ^1.0.8
  gamepads: ^0.1.9
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/knight.png
    - assets/images/thief.png
    - assets/images/wizard.png
    - assets/images/trader.png
    - assets/images/knight_attack.png
    - assets/images/thief_attack.png
    - assets/images/wizard_attack.png
    - assets/images/trader_attack.png
    - assets/images/brick.png
    - assets/images/ground.png
    - assets/images/brick_tile.png
    - assets/images/ground_tile.png
    - assets/maps/
    - assets/maps/level_1.json
    - assets/maps/level_2.json
    - assets/maps/level_3.json
